- name: iTerm custom settings file
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ ansible_env.PWD }}/roles/karl_mac/files"

- name: Sublime Text 3 settings
  git:
    repo: https://github.com/karlhedins/sublime-text-settings.git
    dest: "~/Library/Application Support/Sublime Text 3/Packages/User"
