- name: dotfiles dirs
  file:
    path: "~/.{{ item }}"
    state: directory
  loop:
    - ipython
    - ipython/profile_default
    - ipython/profile_default/startup
    - config

- name: dotfiles links
  file:
    src: "{{ ansible_env.PWD }}/roles/karl_mac/files/dotfiles/{{ item }}"
    path: "~/.{{ item }}"
    state: link
  loop:
    - config/karabiner
    - ansible.cfg
    - slate
    - ipython/profile_default/startup/00-imports.py
# - name: zsh - git repo for prezto fork
#   git:
#     repo: git@github.com:adamchainz/prezto.git
#     dest: ~/.zprezto

# - name: zsh - link in prezto files
#   file:
#     state: link
#     src: "~/.zprezto/runcoms/{{ item }}"
#     path: "~/.{{ item }}"
#   loop:
#     - zlogin
#     - zlogout
#     - zprofile
#     - zshenv
#     - zshrc
#     - zpreztorc
